from __future__ import annotations

import argparse
import csv
from pathlib import Path


def read_csv(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def main() -> None:
    parser = argparse.ArgumentParser(description="Write a compact ablation summary.")
    parser.add_argument("--candidate-csv", type=Path, required=True)
    parser.add_argument("--tracking-csv", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    candidate_rows = read_csv(args.candidate_csv)
    tracking_rows = read_csv(args.tracking_csv) if args.tracking_csv else []
    lines = [
        "# Ablation Summary",
        "",
        "This file was generated by `tools/make_ablation_readme.py`.",
        "",
        "## Candidate-Level Association",
        "",
        "| Setting | Top-1 | Hard Top-1 | Structure Top-1 | Hard Structure Top-1 | Notes |",
        "|---|---:|---:|---:|---:|---|",
    ]
    for row in candidate_rows:
        mode = row.get("gate_mode", row.get("variant", ""))
        lines.append(
            f"| {mode} | {float(row.get('full_top1', 0)):.6f} | "
            f"{float(row.get('hard_full_top1', 0)):.6f} | "
            f"{float(row.get('structure_top1', 0)):.6f} | "
            f"{float(row.get('hard_structure_top1', 0)):.6f} | Top-1 accuracy; hard samples have small center-distance gaps |"
        )
    if tracking_rows:
        lines.extend([
            "",
            "## Tracking-Level Ablation",
            "",
            "| Tracker | Pt-HOTA | Pt-IDF1 | Pt-AssA | Pt-MOTA | IDs | FP | FN |",
            "|---|---:|---:|---:|---:|---:|---:|---:|",
        ])
        for row in tracking_rows:
            lines.append(
                f"| {row.get('tracker', '')} | {float(row.get('Pt-HOTA', 0)):.6f} | "
                f"{float(row.get('Pt-IDF1', 0)):.6f} | {float(row.get('Pt-AssA', 0)):.6f} | "
                f"{float(row.get('Pt-MOTA', 0)):.6f} | {float(row.get('Pt-IDs', 0)):.0f} | "
                f"{float(row.get('Pt-FP', 0)):.0f} | {float(row.get('Pt-FN', 0)):.0f} |"
            )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[DONE] {args.output}")


if __name__ == "__main__":
    main()
